### ISSUE TITLE
Why do not you use Async Await instead of callback in Mongoose statics ?

### ISSUE THREAD

**Issue by annibuliful** [rayriffy/mnet-api#6]
I found this solution [Async Await Mongoose statis](https://gist.github.com/niksumeiko/f551eeb57a509bc27f9372978055c2e6)

**Comment by rayriffy** [comment]
I'll fix this after finshed 'Phase 1' progress.

**Comment by rayriffy** [comment]
Refactoring now. Pull request will be issue soon.
